server:
  port: 80

spring:
  application:
    name: cloud-consume-order

eureka:
  client:
    register-with-eureka: true
    fetchRegister: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka