server:
  port: 8006

spring:
  application:
    name: cloud-provider-paymentconsul8006
  cloud:
    consul:
      host: 192.168.123.128
      port: 8500
      discovery:
        #服务的名称
        service-name: ${spring.application.name}
        #指定开启ip地址注册
        prefer-ip-address: true
        heartbeat:
          enabled: true