server:
  port: 7001

eureka:
  instance:
    hostname: localhost #eureka 服务端的实例名称
  client:
    # false 表示不注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，我的职责就是维护服务实例， 并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与 eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      # 注意地址不能和实例名称重复 不然无法识别
      #集群指向别人
      defaultZone: http://127.0.0.1:7002/eureka/
#      单机指向自己
#      defaultZone: http://127.0.0.1:7001/eureka/
  server:
    # 禁用自我保护机制，保证不可用服务及时剔除
    enable-self-preservation: false
    # 删除时间
    eviction-interval-timer-in-ms: 2000