server:
  port: 7001

eureka:
  instance:
    hostname: localhost #eureka 服务端的实例名称
  client:
    # false 表示不注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，我的职责就是维护服务实例， 并不需要去检索服务
    fetch-register: false
    service-url:
      # 设置与 eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/