server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer-2
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称， 用于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的 相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.123.128
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的exchange名称类型
          content-type: application/json # 设置消息类型，本次为json， 文本设置为 "text/plain"
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: consumerA

eureka:
  client: # 客户端进行eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka
    instance:
      lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔 (默认是30s)
      lease-expiration-duration-in-seconds: 5 # 如果现在超过5s的间隔 (默认92s)
      instance-id: receive-8803.com
      prefer-ip-address: true