server:
  port: 7002

eureka:
  instance:
    hostname: localhost # eureka 实例名称
  client:
    # 是否向注册中心注册自己
    register-with-eureka: false
    # 是否需要检索服务， 注册中心的职责在于维护服务, 所以就不用检索
    fetch-registry: false
    service-url:
      # 设置 eureka的 地址, 注册和查询服务都需要这个地址
      defaultZone: http://127.0.0.1:7001/eureka
