server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由功能， 利用微服务名进行转发
      routes:
        - id: payment_routh # payment_route 路由的ID,沒有固定的规则但要求唯一,建议配合服务名
#          uri: http://localhost:8001 # 匹配后提供服务的地址
          uri: lb://cloud-payment-service # 匹配后提供服务的地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由

        - id: payment_routh_2 # payment_route 路由的ID,沒有固定的规则但要求唯一
          uri: lb://cloud-payment-service # 匹配后提供服务的地址
          predicates:
              - Path=/payment/lb/** # 断言，路径相匹配的进行路由
              - After=2021-03-01T23:30:01.449695800+08:00[Asia/Shanghai] # 这个路由在什么时间后生效
              - Cookie=username,yyzz
              - Header=X-Request-Id, \d+ # 请求头必须包含X-Request-Id字段且值为正数
#              - Before=2021-03-01T23:30:01.449695800+08:00[Asia/Shanghai]
#              - Between=2021-03-01T23:30:01.449695800+08:00[Asia/Shanghai],2021-03-02T23:30:01.449695800+08:00[Asia/Shanghai]

eureka:
  instance:
    instance-id: cloud-gateway-service
  client: # 服务提供者provider注册进eureka服务列表中
    register-with-eurake: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
