server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    register-with-eureka: true
    fetchRegister: true
    service-url:
      # 集群指向所有服务端 单机指向一个就好
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true # 访问路径显示 ip 地址
    # eureka 客户端向服务端发送信条的时间间隔， 默认30s
    lease-renewal-interval-in-seconds: 1
    # eureka 服务端收到最后一次心跳后等待时间上限，默认90s， 超出剔除服务
    lease-expiration-duration-in-seconds: 2

